#!/bin/bash
#####################################################################################
# Execute VDMJ jar with various options
#####################################################################################

# The installation directory containing VDMJ jars
JARDIR=C:/Cygwin/home/lib

# Details for 64-bit Java
JAVA64="/cygdrive/c/Program Files/Java/jre7/bin/javaw.exe"
JAVA64_VMOPTS="-Xmx3000m -Xss5m"

# Details for 32-bit Java
JAVA32="/cygdrive/C/Program Files (x86)/Java/jre8/bin/javaw.exe"
JAVA32_VMOPTS="-Xmx1000m -Xss5m"

# Set defaults as 32-bit standard precision
JAVA=$JAVA32
JAVA_VMOPTS=$JAVA32_VMOPTS
PRECISION=""
VDMJ_OPTS="-path $JARDIR/stdlib"
VERSION="[0-9.]*"
BUILD="[0-9]*"

# Process non-VDMJ options
while [ $# -gt 0 ]
do
    case "$1" in
		--help)
			echo "Usage: $0 [--help] [-P] [-32|-64] [-Vn.n.n] [-Byymmdd] <VDMJ options>"
			echo "Java 32-bit is $JAVA32 $JAVA32_VMOPTS"
			echo "Java 64-bit is $JAVA64 $JAVA64_VMOPTS"
			echo "VDMJ installation is $JARDIR"
			echo "VDMJ default arguments are $VDMJ_OPTS"
			exit 0
			;;
        -P)
			PRECISION="-P"
            ;;
        -32)
			JAVA=$JAVA32
			JAVA_VMOPTS=$JAVA32_VMOPTS
			;;
		-64)
			JAVA=$JAVA64
			JAVA_VMOPTS=$JAVA64_VMOPTS
			;;
		-V*)
			VERSION=${1:2}
			;;
		-B*)
			BUILD=${1:2}
			;;
		*)
			VDMJ_OPTS="$VDMJ_OPTS $1"
    esac
	shift
done

# Locate the latest jar
VDMJ_JAR=$(ls -t $JARDIR/vdmj-*.jar | sed -ne "/vdmj-${VERSION}${PRECISION}-${BUILD}.jar/p" | head -1)

if [ -z "$VDMJ_JAR" ]
then
	echo "Cannot locate $JARDIR/vdmj-${VERSION}${PRECISION}-${BUILD}.jar"
	exit 1
fi

# Allow JMX for VisualVM
VDMJ_VMOPTS="$VDMJ_VMOPTS -Dcom.sun.management.jmxremote=true"
VDMJ_VMOPTS="$VDMJ_VMOPTS -Dcom.sun.management.jmxremote.authenticate=false"
VDMJ_VMOPTS="$VDMJ_VMOPTS -Dcom.sun.management.jmxremote.ssl=false"
VDMJ_VMOPTS="$VDMJ_VMOPTS -Dcom.sun.management.jmxremote.port=16001"

# The dialect is based on $0, so hard-link this file as vdmsl, vdmpp and vdmrt.
DIALECT=$(basename $0)

# Keep rlwrap output in a separate folder
export RLWRAP_HOME=~/.vdmj

# Execute the JVM...
exec rlwrap "$JAVA" $JAVA_VMOPTS $VDMJ_VMOPTS -jar $VDMJ_JAR -$DIALECT $VDMJ_OPTS "$@"


